[canvas.size]
width = 800
height = 600

[canvas.chunks]
size = 16

[ratelimits]
cooldown = 300_000 # 5 minutes in milliseconds

[websockets]
port = 3000
host = "localhost"

[disk]
# Interval in milliseconds between each save
interval = 4000
# Path to the save file
path = "data/map.bin"

[logging]
level = "info"
